version: '3.8'
services:
  mongo:
    image: mongo
    container_name: mongo-container
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    networks:
      - mongo-network

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${ME_CONFIG_MONGODB_ADMINUSERNAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${ME_CONFIG_MONGODB_ADMINPASSWORD}
      ME_CONFIG_MONGODB_SERVER: mongo-container
    ports:
      - "8081:8081"
    networks:
      - mongo-network

  node-app:
    build: .  # Build your Node.js app from a Dockerfile in the current directory
    environment:
      MONGO_USERNAME: ${MONGO_USERNAME}
      MONGO_PASSWORD: ${MONGO_PASSWORD}
      MONGO_HOST: mongo-container
      MONGO_DB: ${MONGO_DB}
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    networks:
      - mongo-network

networks:
  mongo-network:
    driver: bridge
