services:
  mongo:
    image: mongo
    container_name: mongo-container
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    networks:
      - mongo-network

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      ME_CONFIG_MONGODB_SERVER: mongo-container
    ports:
      - "8081:8081"
    networks:
      - mongo-network

  node-app:
    build: .
    container_name: video-call-app
    ports:
      - "3000:3000"  # Add this line
    environment:
      MONGO_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_HOST: mongo-container
      MONGO_DB: ${MONGO_DB}
      NODE_ENV: production
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
      - ./cloudflared:/etc/cloudflared:ro
    depends_on:
      - mongo
    networks:
      - mongo-network

networks:
  mongo-network:
    driver: bridge